name: Publish API Package
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Tag release
        id: tag
        run: |
          version=$(python -c 'import tomllib; from pathlib import Path; print(tomllib.load(Path("pyproject.toml").open("rb"))["project"]["version"])' | tr -d " \n\r\t")
          git tag $version
          git push origin $version && echo "release=true" >> "$GITHUB_OUTPUT" || exit 0
      # Skipped if the tag already exists
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        if: steps.tag.outputs.release
      - name: Build
        run: uv build
        if: steps.tag.outputs.release
      - name: Publish
        run: uv publish
        if: steps.tag.outputs.release
